name: FiguraAuthProvider
version: '${version}'
main: top.mrxiaom.figura.authprovider.PluginMain
api-version: 1.13
softdepend:
  - Vault
  - AuthMe
authors: [ MrXiaoM ]
commands:
  figuraauthprovider:
    description: Main command of FiguraAuthProvider
    aliases:
      - fap
